### ISSUE TITLE
 Anvil doesn't compile on Windows due to IPC

### ISSUE THREAD

**Issue by hosseinmirzapur** [Cyfrin/foundry-simple-storage-f23#1]
Hey guys!

Just in case, if anyone ran into this error while installing foundry components directly from their Github simply use this command and you'll be fine (i'm sharing this cuz it took me 2 hours to find the reason):

```bash
$ cargo install --git https://github.com/foundry-rs/foundry --locked anvil --features ethers/ipc
```

This command will fetch the latest dependencies from the master branch of foundry github and simply be adequate to handle the error. Then after the command succeeded you can ``` foundryup ``` and/or follow along.

Thanks everyone and enjoy the lovely course!

**Comment by PatrickAlphaC** [comment]
Hello! Thanks for making this issue. What lesson did you run into this on? I'll add it to `Chronological_updates.md` in the main repo.

**Comment by hosseinmirzapur** [comment]
> Hello! Thanks for making this issue. What lesson did you run into this on? I'll add it to `Chronological_updates.md` in the main repo.

Hello!
I faced this problem watching [lesson 6](https://youtu.be/umepbfKp5rI?t=22980) while I was trying to build foundry from source code on my windows (without using WSL). When I tried to run:
```bash
# install Anvil
cargo install --path ./anvil --profile local --force
```
As it was in the [documentation](https://book.getfoundry.sh/getting-started/installation#building-from-source), the compile and build process took a while and then failed due to an IPC error.

**Comment by PatrickAlphaC** [comment]
Added here: https://github.com/Cyfrin/foundry-full-course-f23/blob/main/chronological-updates.md#lesson-6

Thank you!
