### ISSUE TITLE
i cant deploy my contract using anvil

### ISSUE THREAD

**Issue by utkarsh1507** [Cyfrin/foundry-simple-storage-f23#17]
gitpod /workspace/Foundry/foundry-project (main) $ forge script script/DeploySimpleStorage.s.sol
[⠊] Compiling...
No files changed, compilation skipped
Error: 
Could not find target contract

**Comment by Equious** [comment]
Please open a discussion on the repo or seek help in Discord. Please include far more details to allow us to assist. This error points to your configured target contract not being found.
