### ISSUE TITLE
forge build --zksync does not output anything

### ISSUE THREAD

**Issue by RomThpt** [Cyfrin/foundry-simple-storage-f23#18]
# Description : 
After installing **foundryup-zksync**, running `forge build --zksync` does not produce any output—it only results in a newline. This prevents successful compilation with zkSync support.

## Steps to Reproduce :
1.	Install foundryup-zksync.
2.	Run:
```bash
foundryup-zksync
forge build --zksync
```
4.	Observe that the command produces no output, only a newline.

## Expected Behavior
Expected the build process to compile the files with zkSync configuration or to provide an error if setup was incomplete.

## Actual Behavior
The command results in no output, only moving to a new line without feedback.

Troubleshooting Steps Tried

- Verified foundryup-zksync installation by checking forge --version which shows forge 0.0.2.
- Reinstalled foundryup-zksync and tried other commands (e.g., forge test), which work as expected.

Environment

- Operating System: macOS Sequoia 15.0.1
- Foundry Version: forge 0.2.0
- Foundry-zksync Version: 0.0.2
- git Version: 2.39.5 (Apple Git-154)

## Additional Context
This issue occurs in a local environment on macOS. Please let me know if additional logs or screenshots would help.

**Comment by Equious** [comment]
Sorry for the delayed follow up here. Gotta encourage coding questions to be posted in Discussions. Also welcome to ask in [Discord](https://discord.gg/6Vj6fpeR).

I can't speak specifically to functionality in a MacOS environment. I can say that the ZKsync integration has a couple hiccups. Potentially the ZKSync repo has similar reports, have you checked?
