### ISSUE TITLE
Compiler version must be fixed 

### ISSUE THREAD

**Issue by lalondelalonde** [Cyfrin/foundry-simple-storage-f23#2]
Hello guys, awesome course!

- Currently at lesson 6. Foundry ran properly. 
- Forge, Anvil, Cast and Chisel are installed.
- The issue occur when I copy paste SimpleStorage.sol in src:

```
4:1: SyntaxError: Source file requires different compiler version (current compiler is 0.4.17+commit.bdeb9e52.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version\npragma solidity 0.8.19;\n^---------------------^\n",
	"startLineNumber": 4,
	"startColumn": 2,
	"endLineNumber": 4,
	"endColumn": 2
}]
```

I also have compiler version must be fixed.

It's been a couple of hours that I'm stuck on this and can't seems to find what I must do. 

Tried to reinstalled solc but everytime I do so and look for the version I receive: command not found.

Not sure but since Foundry seems to have an integrated compiler (I'm beginning guys) I think that might be the reason why. I'm also running the code on a MacBook Pro High Sierra which I think might be the issue.

Any suggestions?

**Comment by PatrickAlphaC** [comment]
Hello! Thanks for making this issue. 

Can you:
1. Make this a discusson on the full repo? https://github.com/Cyfrin/foundry-full-course-f23/discussions

Thank you!

**Comment by lalondelalonde** [comment]
Surely will! 

Thank you for diligence and generosity Patrick, sincerely appreciate it.
