### ISSUE TITLE
Cast Call for interacting with deployed contract

### ISSUE THREAD

**Issue by miladad8** [Cyfrin/foundry-simple-storage-f23#8]
I'm trying to interact with a deployed contract using terminal in VS code. I can successfully deploy a  contract. `cast send` command also works fine with `store()` function. but when I try to use `cast call` for `retrieve()` function, I get `0x` everytime.below is my code:

`
cast call 0x90193C961A926261B756D1E5bb255e67ff9498A1 "retrieve()"
`

but all I get is:

`0x`

I have also tried to store different values and then retrieve them, but nothings changed.
I also check the `retrieve()` spelling and copy the exact function name from the main contract.

Any help would be appreciated.

**Comment by PatrickAlphaC** [comment]
Hello! Thanks for making this issue. 

Can you:
1. Make this a discusson on the full repo? https://github.com/Cyfrin/foundry-full-course-f23/discussions

2. Could you please remember to follow this section to format your questions? https://youtu.be/umepbfKp5rI?t=22464

**Comment by steinitz** [comment]
This would seem an ideal place for @miladad8 's question.  It has tighter context than at the top level.  Can you help me understand why you want it at the top level?

**Comment by PatrickAlphaC** [comment]
We have people who monitor discussions, seems like this is more of a discussion about why their tool isn't working vs an issue with the repo @steinitz.

Normally, issues are a great place to discuss.

**Comment by steinitz** [comment]
Makes good sense @PatrickAlphaC.  Thanks, and a heartfelt thanks for your effective and entertaining courses.

For anyone encountering this, a similar topic is, indeed, [now in a Discussion at the course top level](https://github.com/Cyfrin/foundry-full-course-cu/discussions/459)
